### ISSUE TITLE
Failed to parse Webhook URL

### ISSUE THREAD

**Issue by VictorBrek** [Riku32/DiscordLink#12]
When I try to run DiscordLink on my 1.17 Minecraft Server, It Enables DiscordLink, then spits a load of java errors.
Its running on a Debian Linux host with Java 16

```
[02:46:44] [Server thread/ERROR]: Error occurred while enabling DiscordLink v1.2 (Is it up to date?)
java.lang.IllegalArgumentException: Failed to parse webhook URL
        at club.minnced.discord.webhook.WebhookClient.withUrl(WebhookClient.java:121) ~[?:?]
        at com.github.riku32.discordlink.DiscordLink.onEnable(DiscordLink.java:79) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.17.jar:3151-Spi
got-101ebb6-68d4031]                                                                                           at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) [spigot-1.17
.jar:3151-Spigot-101ebb6-68d4031]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) [spigot-1.1
7.jar:3151-Spigot-101ebb6-68d4031]                                                                             at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495) [spigot-1.17.
jar:3151-Spigot-101ebb6-68d4031]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409) [spigot-1.17.jar:3151-Spigot-101ebb6-68d4031]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:233) [spigot-1.17.jar:3151-Spigot-101ebb6-68d4031]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:987) [spigot-1.17.jar:3151-Spigo
t-101ebb6-68d4031]                                                                                             at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) [spigot-1.17.jar:315
1-Spigot-101ebb6-68d4031]                                                                                      at net.minecraft.server.MinecraftServer$$Lambda$3786/0x000000005c1e1ea8.run(Unknown Source) [sp
igot-1.17.jar:3151-Spigot-101ebb6-68d4031]
        at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by JSH32** [comment]
Send your config, Change a few numbers in the token/webhook though

**Comment by VictorBrek** [comment]
I was stupid and didn't realize I needed to put a webhook url Im so sorry.

**Comment by JSH32** [comment]
No worries lmao. What did you put instead btw, it shouldn't let you pass if your webhook URL was invalid

**Comment by VictorBrek** [comment]
I thought I needed to put another channel ID, and also while I have you, is there a way to ping a discord user from minecraft?

**Comment by JSH32** [comment]
At the moment no, its to prevent everyone pings. I'll make a toggle after I finish rewriting the base
