### ISSUE TITLE
Join doesn't send join message

### ISSUE THREAD

**Issue by tionis** [Riku32/DiscordLink#15]
## Description
When a player joins, no join message is sent in Discord.  
Leave and Death messages work though.

## To Reproduce
1. Use paper as Minecraft server
2. Setup plugin with token/webhooks
3. Have one join message after linking
4. No more join messages are sent after now

**Comment by JSH32** [comment]
Right now discordlink is going through a large scale rewrite so this will probably get fixed the next spigot update. Is there a message in your console log?

**Comment by tionis** [comment]
I was just going through my logs as I totally forgot to read them carefully and the error seems to be caused by this. I now gave the bot all permissions, and it now works as expected. I'm just not sure why it requires ban permissions for player join events.
```
[16:06:02 ERROR]: Could not pass event PlayerJoinEvent to DiscordLink v1.2                                                                                 
net.dv8tion.jda.api.exceptions.InsufficientPermissionException: Cannot perform action due to a lack of Permission. Missing permission: BAN_MEMBERS
        at net.dv8tion.jda.internal.entities.GuildImpl.retrieveBanById(GuildImpl.java:762) ~[?:?]        
        at net.dv8tion.jda.api.entities.Guild.retrieveBan(Guild.java:2460) ~[?:?]                         
        at com.github.riku32.discordlink.events.PlayerActivity.lambda$onPlayerJoin$10(PlayerActivity.java:89) ~[?:?]                                      
        at net.dv8tion.jda.internal.requests.DeferredRestAction.queue(DeferredRestAction.java:138) ~[?:?]             
        at com.github.riku32.discordlink.events.PlayerActivity.onPlayerJoin(PlayerActivity.java:87) ~[?:?]               
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.17.1.jar:git-Paper-140]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-140]       
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-140]          
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Paper-140]
        at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:359) ~[patched_1.17.1.jar:git-Paper-140]                                                     
        at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:301) ~[patched_1.17.1.jar:git-Paper-140]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:307) ~[?:?]    
        at net.minecraft.network.Connection.tick(Connection.java:399) ~[?:?]                                                                               
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:196) ~[?:?]          
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1578) ~[patched_1.17.1.jar:git-Paper-140]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-140]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Paper-140]                                                         
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[patched_1.17.1.jar:git-Paper-140]                                                          
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-140]                                                       
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by tionis** [comment]
I will close this though as it was my mistake.
